# Generated by Django 5.2.1 on 2025-05-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contactmessage_responded_contactmessage_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='responded',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='response',
        ),
    ]
