# Generated by Django 5.2.1 on 2025-05-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactmessage_responded_at_contactmessage_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='response',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
