# Generated by Django 5.2.1 on 2025-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contactmessage_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='responded',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
