# Generated by Django 5.2.1 on 2025-05-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_faqcategory_slug_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
