# Generated by Django 5.2.1 on 2025-05-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_faqcategory_description_faqquestion_delete_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqquestions', to='main.faqcategory'),
        ),
        migrations.AlterField(
            model_name='faqquestion',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
