# Generated by Django 5.2.1 on 2025-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_faqquestion_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqcategory',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
