# Generated by Django 5.2.1 on 2025-05-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_faqcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('button_text', models.CharField(max_length=100, verbose_name='Button Text')),
                ('button_link', models.URLField(verbose_name='Button Link')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Hero Image')),
            ],
        ),
    ]
