# Generated by Django 5.2.1 on 2025-05-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
