# Generated by Django 5.2.1 on 2025-05-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_herosection_button_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Sections'},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='image',
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='hero_images/', verbose_name='Fon Şəkli'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_url',
            field=models.CharField(default='#services', max_length=200, verbose_name='Düymə Linki'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(default='Ətraflı', max_length=100, verbose_name='Düymə Mətni'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(verbose_name='Təsvir'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlıq'),
        ),
    ]
