# Generated by Django 5.2 on 2025-05-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatableText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unikal açar (məsələn, navbar_home, hero_title və s.)', max_length=100, unique=True)),
                ('lang', models.CharField(choices=[('az', 'Azərbaycan'), ('en', 'English'), ('ru', 'Русский')], max_length=2)),
                ('text', models.TextField()),
            ],
        ),
    ]
