# Generated by Django 5.2 on 2025-05-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_translatabletext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslatableText',
        ),
    ]
